www-client/chromium: add `python_export_utf8_locale`
Chromium requires a UTF-8 locale to build as certain python build
scripts in (e.g.) Blink actually need to write out Unicode characters.

This should prevent build failures like the following:

	UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c'
	in position 116760: ordinal not in range(256)

Bug: https://bugs.gentoo.org/974799
Signed-off-by: Matt Jolly <kangie@gentoo.org>