mail-filter/rspamd: depend on older doctest for all versoins
On the binhost, we hit with 3.14.3:
```
/usr/include/doctest/doctest.h:1277:32: error: passing ‘const rspamd::mime::basic_mime_string<char>’ as ‘this’ argument discards qualifiers [-fpermissive]
 1277 |         for (auto it = in.begin(); it != in.end(); ++it) {
      |                        ~~~~~~~~^~
```

Bug: https://bugs.gentoo.org/973396
Signed-off-by: Sam James <sam@gentoo.org>